"""Create or verify thin agent adapters for the canonical AGENTS.md contract."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]

CLAUDE_ADAPTER = """<!-- Generated by scripts/setup_agents.py. Do not edit directly. -->
@AGENTS.md
"""

CURSOR_ADAPTER = """---
description: Follow the canonical Career Harness agent contract
alwaysApply: true
---

<!-- Generated by scripts/setup_agents.py. Do not edit directly. -->

Read and follow [AGENTS.md](../../AGENTS.md) as the canonical repository instructions.
Do not duplicate or override its rules in this adapter.
Use `.agents/skills/` as the canonical project skill directory.
"""

ADAPTERS = {
    Path("CLAUDE.md"): CLAUDE_ADAPTER,
    Path(".cursor/rules/career-harness.mdc"): CURSOR_ADAPTER,
}


def validate_canonical_files(repository_root: Path) -> list[str]:
    """Return errors for missing canonical instruction and skill locations."""
    errors: list[str] = []
    required_paths = (
        repository_root / "AGENTS.md",
        repository_root / "harness.yaml",
        repository_root / ".agents" / "skills",
    )
    for required_path in required_paths:
        if not required_path.exists():
            errors.append(f"missing canonical path: {required_path.relative_to(repository_root)}")
    return errors


def check_adapters(repository_root: Path) -> list[str]:
    """Return errors when an adapter is missing or differs from generated content."""
    errors = validate_canonical_files(repository_root)
    for relative_path, expected_content in ADAPTERS.items():
        adapter_path = repository_root / relative_path
        if not adapter_path.is_file():
            errors.append(f"missing adapter: {relative_path}")
            continue
        actual_content = adapter_path.read_text(encoding="utf-8")
        if actual_content != expected_content:
            errors.append(f"adapter drift: {relative_path}")
    return errors


def write_adapters(repository_root: Path) -> None:
    """Write generated adapters without copying the canonical instructions."""
    canonical_errors = validate_canonical_files(repository_root)
    if canonical_errors:
        raise RuntimeError("\n".join(canonical_errors))

    for relative_path, content in ADAPTERS.items():
        adapter_path = repository_root / relative_path
        adapter_path.parent.mkdir(parents=True, exist_ok=True)
        adapter_path.write_text(content, encoding="utf-8")
        print(f"updated {relative_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create or check Claude Code and Cursor adapters for AGENTS.md."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check for missing or drifted adapters without changing files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.check:
        errors = check_adapters(REPOSITORY_ROOT)
        if errors:
            for error in errors:
                print(error, file=sys.stderr)
            return 1
        print("agent adapters are synchronized")
        return 0

    try:
        write_adapters(REPOSITORY_ROOT)
    except RuntimeError as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
